class CreateLocationPostcodes < ActiveRecord::Migration
  def self.up
    create_table :location_postcodes do |t|
      t.column  :postcode_text,   :string
      t.timestamps
  end
  LocationPostcode.create(:postcode_text => "BT1")
  LocationPostcode.create(:postcode_text => "BT2")
  LocationPostcode.create(:postcode_text => "BT3")
  LocationPostcode.create(:postcode_text => "BT4")
  LocationPostcode.create(:postcode_text => "BT5")
  LocationPostcode.create(:postcode_text => "BT6")
  LocationPostcode.create(:postcode_text => "BT7")
  LocationPostcode.create(:postcode_text => "BT8")
  LocationPostcode.create(:postcode_text => "BT9")
  LocationPostcode.create(:postcode_text => "BT10")
  LocationPostcode.create(:postcode_text => "BT11")
  LocationPostcode.create(:postcode_text => "BT12")
  LocationPostcode.create(:postcode_text => "BT13")
  LocationPostcode.create(:postcode_text => "BT14")
  LocationPostcode.create(:postcode_text => "BT15")
  LocationPostcode.create(:postcode_text => "BT16")
  LocationPostcode.create(:postcode_text => "BT17")
  LocationPostcode.create(:postcode_text => "BT18")
  LocationPostcode.create(:postcode_text => "BT19")
  LocationPostcode.create(:postcode_text => "BT20")
  LocationPostcode.create(:postcode_text => "BT21")
  LocationPostcode.create(:postcode_text => "BT22")
  LocationPostcode.create(:postcode_text => "BT23")
  LocationPostcode.create(:postcode_text => "BT24")
  LocationPostcode.create(:postcode_text => "BT25")
  LocationPostcode.create(:postcode_text => "BT26")
  LocationPostcode.create(:postcode_text => "BT27")
  LocationPostcode.create(:postcode_text => "BT28")
  LocationPostcode.create(:postcode_text => "BT29")
  LocationPostcode.create(:postcode_text => "BT30")
  LocationPostcode.create(:postcode_text => "BT31")
  LocationPostcode.create(:postcode_text => "BT32")
  LocationPostcode.create(:postcode_text => "BT33")
  LocationPostcode.create(:postcode_text => "BT34")
  LocationPostcode.create(:postcode_text => "BT35")
  LocationPostcode.create(:postcode_text => "BT36")
  LocationPostcode.create(:postcode_text => "BT37")
  LocationPostcode.create(:postcode_text => "BT38")
  LocationPostcode.create(:postcode_text => "BT39")
  LocationPostcode.create(:postcode_text => "BT40")
  LocationPostcode.create(:postcode_text => "BT41")
  LocationPostcode.create(:postcode_text => "BT42")
  LocationPostcode.create(:postcode_text => "BT43")
  LocationPostcode.create(:postcode_text => "BT44")
  LocationPostcode.create(:postcode_text => "BT45")
  LocationPostcode.create(:postcode_text => "BT46")
  LocationPostcode.create(:postcode_text => "BT47")
  LocationPostcode.create(:postcode_text => "BT48")
  LocationPostcode.create(:postcode_text => "BT49")
  LocationPostcode.create(:postcode_text => "BT50")
  LocationPostcode.create(:postcode_text => "BT51")
  LocationPostcode.create(:postcode_text => "BT52")
  LocationPostcode.create(:postcode_text => "BT53")
  LocationPostcode.create(:postcode_text => "BT54")
  LocationPostcode.create(:postcode_text => "BT55")
  LocationPostcode.create(:postcode_text => "BT56")
  LocationPostcode.create(:postcode_text => "BT57")
  LocationPostcode.create(:postcode_text => "BT58")
  LocationPostcode.create(:postcode_text => "BT59")
  LocationPostcode.create(:postcode_text => "BT60")
  LocationPostcode.create(:postcode_text => "BT61")
  LocationPostcode.create(:postcode_text => "BT62")
  LocationPostcode.create(:postcode_text => "BT63")
  LocationPostcode.create(:postcode_text => "BT64")
  LocationPostcode.create(:postcode_text => "BT65")
  LocationPostcode.create(:postcode_text => "BT66")
  LocationPostcode.create(:postcode_text => "BT67")
  LocationPostcode.create(:postcode_text => "BT68")
  LocationPostcode.create(:postcode_text => "BT69")
  LocationPostcode.create(:postcode_text => "BT70")
  LocationPostcode.create(:postcode_text => "BT71")
  LocationPostcode.create(:postcode_text => "BT72")
  LocationPostcode.create(:postcode_text => "BT73")
  LocationPostcode.create(:postcode_text => "BT74")
  LocationPostcode.create(:postcode_text => "BT75")
  LocationPostcode.create(:postcode_text => "BT76")
  LocationPostcode.create(:postcode_text => "BT77")
  LocationPostcode.create(:postcode_text => "BT78")
  LocationPostcode.create(:postcode_text => "BT79")
  LocationPostcode.create(:postcode_text => "BT80")
  LocationPostcode.create(:postcode_text => "BT81")
  LocationPostcode.create(:postcode_text => "BT82")
  LocationPostcode.create(:postcode_text => "BT83")
  LocationPostcode.create(:postcode_text => "BT84")
  LocationPostcode.create(:postcode_text => "BT85")
  LocationPostcode.create(:postcode_text => "BT86")
  LocationPostcode.create(:postcode_text => "BT87")
  LocationPostcode.create(:postcode_text => "BT88")
  LocationPostcode.create(:postcode_text => "BT89")
  LocationPostcode.create(:postcode_text => "BT90")
  LocationPostcode.create(:postcode_text => "BT91")
  LocationPostcode.create(:postcode_text => "BT92")
  LocationPostcode.create(:postcode_text => "BT93")
  LocationPostcode.create(:postcode_text => "BT94")
  LocationPostcode.create(:postcode_text => "BT95")
  LocationPostcode.create(:postcode_text => "BT96")
  LocationPostcode.create(:postcode_text => "BT97")
  LocationPostcode.create(:postcode_text => "BT98")
  LocationPostcode.create(:postcode_text => "BT99")

end

  def self.down
    drop_table :location_postcodes
  end
end
